
width: 5

characters:
  - char: C
    layout:
      - ".****"
      - "*...."
      - "*...."
      - "*...."
      - "*...."
      - "*...."
      - ".****"
  - char: O
    layout:
      - ".***."
      - "*...*"
      - "*...*"
      - "*...*"
      - "*...*"
      - "*...*"
      - ".***."
  - char: D
    layout:
      - "***.."
      - "*..*."
      - "*...*"
      - "*...*"
      - "*...*"
      - "*..*."
      - "***.."
  - char: E
    layout:
      - "*****"
      - "*...."
      - "*...."
      - "*****"
      - "*...."
      - "*...."
      - "*****"
  - char: S
    layout:
      - ".****"
      - "*...."
      - "*...."
      - ".***."
      - "....*"
      - "....*"
      - "****."
  - char: M
    layout:
      - "*...*"
      - "**.**"
      - "*.*.*"
      - "*.*.*"
      - "*...*"
      - "*...*"
      - "*...*"